#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#模块的第一个未注释的字符串被默认为文档注释
'a test module'

#表示当前写这个文档的作者
__author__ = 'Happy Li'

#导入系统模块
import sys

def test():
	args = sys.argv
	if len(args)==1:
		print('Hello,World!')
	elif len(args)==2:
		print('Hello,%s!' % args[1])
	else:
		print('Too many arguments')
#这句条件判断表明当使用命令行直接调用该模块时此时__name__的职位__main__
if __name__=='__main__':
	test()
#对于模块的理解
#首先模块是将不同功能块分开这样来更易维护
#当我们用命令行来调用该模块时，argv[0]表示 对应的python文件名,argv[1....]表示文件名字的参数